### ISSUE TITLE
return runtime information

### ISSUE THREAD

**Issue by goern** [goern/thoth-dependency-monkey#26]
**Is your feature request related to a problem? Please describe.**
We would like to return the time consumed by a validation.

**Describe the solution you'd like**
The runtime information should be part of the validation

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Comment by ace2107** [comment]
**Describe the solution you have considered :**
import time
start_time = time.time()
main()
print("--- %s seconds ---" % (time.time() - start_time))

Something like this will be integrated as part of the DM script or e2e test script

**Comment by goern** [comment]
it should be part of the REST response when you get a validation by ID
