### ISSUE TITLE
setup.py should include requirements from Pipenv or requirements.txt file

### ISSUE THREAD

**Issue by goern** [goern/thoth-dependency-monkey#8]
Right now there is a fixed list of requirements within setup.py, thats not that clever.

**Comment by ace2107** [comment]
Reading from Pipfile or Pipfile.lock is not a good idea and shouldn't be done. On the other hand some overlapping between requirements and setup is possible , it is not recommended . 

https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py

**Comment by ace2107** [comment]
Though something like this can be a solution .
https://github.com/elgertam/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/setup.py
